services:
  webol:
    image: webol-pc:2
    container_name: webol-cli-server
    restart: no
    environment:
      - RUST_LOG=info,webol=trace
      - WEBOL_TIMEOFFSET=2
    volumes:
      - ./devices:/devices
    network_mode: host
